### PR TITLE
Add alertmanager parser

### PR DESCRIPTION
**Pull request by xenrox**
This creates a message that is similar to the default Email template

### CODE REVIEW

**Comment by tmsmr** [comment]
- Maybe we should name the endpoint `promalerts` or anything that indicates its for Prometheus, what do you think?
- Could you provide an example-payload in https://github.com/xenrox/xmpp-webhook/tree/add-alertmanager/dev?

**Comment by xenrox** [comment]
I added the example payload (here is the complete format: https://prometheus.io/docs/alerting/latest/configuration/#webhook_config) and I renamed the endpoint, but I am not too sure about that. Even though Alertmanager is mostly coupled with Prometheus it can be used without it as well:
https://github.com/prometheus/alertmanager/blob/master/README.md 
"The Alertmanager handles alerts sent by client applications such as the Prometheus server."

**Comment by tmsmr** [comment]
I didn't knew the Alertmanager is so loosely coupled with Prometheus. You are right, we should keep `alertmanager` then.

**Comment by xenrox** [comment]
Ok I changed it back.

**Pull request merged**
